apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tracegarden-preview.fullname" . }}-jobs
  labels:
    {{- include "tracegarden-preview.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [migration, seed]
  policyTypes: [Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "tracegarden-preview.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
