{{ include "tracegarden.validateServiceAccounts" . }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracegarden.observationServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracegarden.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracegarden.logsServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracegarden.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
