apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracegarden.fullname" . }}-web
  labels:
    {{- include "tracegarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tracegarden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracegarden.fullname" . }}-collector
  labels:
    {{- include "tracegarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  type: {{ .Values.service.collector.type }}
  ports:
    - name: http
      port: {{ .Values.service.collector.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tracegarden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: collector
